model: 
  base_learning_rate: 1.0e-06
  target: dualss.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: latent
    cond_stage_key: class_label 
    image_size: 32
    channels: 16 
    cond_stage_trainable: True # 
    conditioning_key: crossattn 
    monitor: val/loss_simple_ema
    use_ema: True 

    unet_config:
      target: dualss.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 8 # 32 # 256
        in_channels: 16
        out_channels: 16
        model_channels: 256 
        channel_mult: 
        - 1
        - 2
        - 4
        attention_resolutions:
        #note: this isn\t actually the resolution but
        # the downsampling factor, i.e. this corresnponds to
        # attention on spatial resolution 8,16,32, as the
        # spatial reolution of the latents is 32 for f8
        - 4
        - 2
        - 1
        num_res_blocks: 2 
        num_head_channels: 32
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim:  512 
    
    first_stage_config:
      target: dualss.models.autoencoder_mask_2decoder_Attention_PINNres.VQModelInterface 
      params:
        n_embed: 8192
        embed_dim: 16
        monitor: "val/rec_loss"
        ckpt_path:
        ddconfig:
          double_z: false
          z_channels: 16
          resolution: 64 # 256
          in_channels: 3
          out_ch: 7 
          ch: 128
          ch_mult: [ 1,2,4,4 ]  # num_down = len(ch_mult)-1
          num_res_blocks: 2
          attn_resolutions: [ ] 
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    
    cond_stage_config: # __is_unconditional__
      target: dualss.modules.encoders.modules.ClassEmbedder
      params:
        n_classes: 1
        embed_dim: 512 
        key: class_label

data:
  target: main_train_generator.DataModuleFromConfig
  params:
    batch_size: 4 # 32 # 64
    num_workers: 4 # 16
    wrap: True 
    train:
      target: dualss.data.tongue.TongueTrain 
      params:
          size: 64 # 256
          dir_or_csv: csv
          all_in_memory: True
    validation:
      target: dualss.data.tongue.TongueValidation 
      params:
          size: 64 # 256
          dir_or_csv: csv
          all_in_memory: True

lightning:
  callbacks:
    image_logger:
      target: main_train_generator.ImageLogger
      params:
        batch_frequency: 8000
        max_images: 1
        increase_log_steps: False

  trainer:
    benchmark: True
    accumulate_grad_batches: 2 # 16